name: ci

on: push

jobs:
    dialyzer:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.2.2

            - uses: actions/cache@v4.1.2
              with:
                  key: ${{ github.job }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}
                  path: |
                      _build
                      deps

            - uses: erlef/setup-beam@v1.18.2
              with:
                  elixir-version: ${{ matrix.elixir }}
                  otp-version: ${{ matrix.otp }}

            - run: mix deps.get

            - run: mix compile --warnings-as-errors

            - run: mix dialyzer --format github

            - run: rm -rf _build/dev/lib/postscript

        strategy:
            matrix:
                elixir:
                    - 1.17.x
                    - 1.16.x
                    - 1.15.x

                otp:
                    - 27.x
                    - 26.x
                    - 25.x
                    - 24.x

                exclude:
                    - elixir: 1.15.x
                      otp: 27.x

                    - elixir: 1.16.x
                      otp: 27.x

                    - elixir: 1.17.x
                      otp: 24.x

    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4.2.2

            - uses: actions/cache@v4.1.2
              with:
                  key: ${{ github.job }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('mix.lock') }}
                  path: |
                      _build
                      deps

            - uses: erlef/setup-beam@v1.18.2
              with:
                  elixir-version: ${{ matrix.elixir }}
                  otp-version: ${{ matrix.otp }}

            - run: mix deps.get

            - run: MIX_ENV=test mix compile --warnings-as-errors

            - run: mix test

            - run: rm -rf _build/test/lib/postscript

        strategy:
            matrix:
                elixir:
                    - 1.17.x
                    - 1.16.x
                    - 1.15.x

                otp:
                    - 27.x
                    - 26.x
                    - 25.x
                    - 24.x

                exclude:
                    - elixir: 1.15.x
                      otp: 27.x

                    - elixir: 1.16.x
                      otp: 27.x

                    - elixir: 1.17.x
                      otp: 24.x
